### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by mergen3107** [net00-1/SW-DLT#54] opened 2024-07-15 19:22 UTC
iOS: 17.5.1
Device: iPhone 15 Pro Max
SW-DLT: 3.20.1
Browser: Safari
Method: Share with SW-DLT
Terminal: a-shell Mini (also tried on full with the same result) 

Hi! Thank you very much for SW-DLT!

When trying to download a video, SW-DLT give error:
`Exception Alert
type object 'Consts' has no attribute 'DERROR'`

This a video I never tried to download before this error: https://m.youtube.com/watch?v=jofNR_WkoCE&pp=ygUVd2hhdCBkb2VzIHRoZSBmb3ggc2F5

And this is the video that I was able to download OK in January or February, but now it says `Exception Alert
ERROR: unable to download video data: HTTP
Error 403: Forbidden`
https://m.youtube.com/watch?v=dlYxmRcdLVw&pp=ygURRWFzeSB0aW1pbmcgaHluaXg%3D

**Comment by net00-1** [comment] 2024-08-20 03:22
Duplicate of  #53

**Closed by net00-1** 2024-08-20 03:22 UTC
