### ISSUE TITLE
Issues with downloading audio playlists

### ISSUE THREAD

**Issue by mybubbletea** [net00-1/SW-DLT#23] opened 2022-12-07 22:11 UTC
I have an issue downloading YouTube audio playlists. If I want to download an audio playlist I get: "There was a problem communicating with the app." for the line "Execute runScript" under "If isMini".

**Comment by net00-1** [comment] 2022-12-16 16:58
Which iOS version are you on? Do you have the link that causes the issue?

**Comment by mybubbletea** [comment] 2022-12-16 23:07
Hi, I'm using 16.2 and the link is: https://youtube.com/playlist?list=PLDUrDzhZpPad4GxETQYZmRZ2d2AyV8SfS.

**Comment by net00-1** [comment] 2023-03-03 00:43
Had to close this as you're on iOS 16. I can't reproduce it with my current iOS 15 devices.

**Closed** 2023-03-03 00:43 UTC
Labels: Bug
