### ISSUE TITLE
yt-dlp instead of youtube-dl

### ISSUE THREAD

**Issue by Aditeya** [net00-1/SW-DLT#9] opened 2021-11-27 06:18 UTC
You could change the dependency to use [yt-dlp](https://github.com/yt-dlp/yt-dlp). It should function pretty much the same but have more features and is being actively developed. Also an idea is an option to choose between yt-dlp and youtube-dl.

**Comment by net00-1** [comment] 2021-11-27 14:46
I did attempt to install `yt-dlp` before, but it doesn't seem to work in a-Shell. I tracked the issue down to the `pycryptodomex` dependency that it requires. 

I could technically get around this by not installing any of the dependencies with `--no-deps`, but I haven't tested how much would break without them, or I could try installing as many dependencies as a-Shell supports, but a full yt-dlp install doesn't work yet.

**Comment by Aditeya** [comment] 2021-11-27 17:12
I think that should work. According to the [documentation](https://github.com/yt-dlp/yt-dlp#dependencies), `pycryptodomex` is optional and it doesn't appear to be used a lot. However, you might need the others (esp ffmpeg and ffprobe as mentioned in the doc).

**Comment by jonathanweinberg** [comment] 2021-12-27 03:58
I can confirm that using `--no-deps ` yt-dlp installs fine (stole the command from this issue https://github.com/holzschu/a-shell/issues/331).

Also, note that in at least the full a-Shell (aka not a-Shell mini), ffmpeg and ffprobe is native. Although it seems to have a bug that requires you uninstall and reinstall a-Shell. 

```
ffmpeg
ffmpeg version n4.4-80-gbf87bdd3f6 Copyright (c
) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-
1205.0.22.11)
  configuration: --cc=clang --arch=arm64 --disa
ble-asm --enable-cross-compile --enable-pthread
s --enable-videotoolbox --disable-audiotoolbox 
--enable-libfreetype --enable-libzimg --disable
-network --disable-debug --disable-gpl --disabl
e-nonfree
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i in
file]... {[outfile options] outfile}...
Use -h to get full help or, even better, run 'm
an ffmpeg'
```

**Comment by kiddio** [comment] 2022-01-03 16:21
Also worth mentioning, you can download the YT-DLP binary from their repo and place that in your a-shell file. 

I did that so I could use it in shortcuts.

**Comment by net00-1** [comment] 2022-02-02 02:27
I just got back around to start working on this update. The 3E14 branch is live with yt-dlp integration instead of youtube-dl. Not going to close this yet since there are a some issues to fix with the progress counter and tests.

**Comment by Aditeya** [comment] 2022-02-02 08:09
I've tried the new script a few times and its faster than youtube-dl. There was a error downloading some videos of instagram, but running the shortcut again resolved it.

**Comment by net00-1** [comment] 2022-02-02 23:34
Nice to know, I just got the terminal colors and progress indicators how I wanted. I will start working on the tests, in case I run into that issue.

**Comment by net00-1** [comment] 2022-02-07 05:48
The update to SW-DLT is now live in RoutineHub (or you can update from within the shortcut). I will close this issue now, but feel free to open others if you encounter issues

**Closed by net00-1** 2022-02-07 05:48 UTC
Labels: Bug
